# Generated by Django 4.2 on 2025-08-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
